FROM centos:7

ENV container docker

STOPSIGNAL SIGRTMIN+3

RUN yum -y install epel-release && \
    yum -y update && \
    yum -y install awscli jq iproute ansible make git python-junit_xml python-yaml ansible-lint python-pip && \
    pip install boto boto3 && \
    yum clean all

COPY ./ec2.ini /srv/ec2.ini
COPY ./ec2.py /srv/ec2.py
COPY ./inventory /srv/inventory

RUN chmod +x /srv/ec2.py

ENV EC2_INI_PATH /srv/ec2.ini
ENV ANSIBLE_INVENTORY /srv/ec2.py

WORKDIR /srv/

COPY . /srv
