---
- name: create host inv
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - host_add
  vars_files:
    - vars/var.yml

- name: build environment
  hosts: 34.246.182.240
  become: true
  gather_facts: true
  roles:
    - build_env
  tags:
    - build

- name: deploy artifacts
  hosts: 34.246.182.240
  become: true
  gather_facts: true
  roles:
    - deployment
  tags:
    - deploy
