---
- name: build environment
  hosts: ci
  become: true
  gather_facts: true
  roles:
    - build_env
  tags:
    - build

- name: deploy artifacts
  hosts: ci
  become: true
  gather_facts: true
  roles:
    - deployment
  tags:
    - deploy
