---
- name: create host inv
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - host_add
  vars_files:
    - vars/var.yml

- name: build environment
  hosts: "{{ hostip }}" 
  become: true
  gather_facts: true
  roles:
    - build_env
  tags:
    - build
  vars_files:
    - vars/main.yml

- name: deploy artifacts
  hosts: "{{ hostip }}"
  become: true
  gather_facts: true
  roles:
    - deployment
  tags:
    - deploy
  vars_files:
    - vars/main.yml
