---
- name: create private key file prd
  blockinfile:
    path: /tmp/aws_key.pem
    block: "{{ private_key }}"
    create: yes
    mode: 0400

- name: add inventory groups
  add_host:
    name: "54.229.114.204"
    groups: java_server
    ansible_ssh_private_key_file: /tmp/aws_key.pem
    ansible_user: ubuntu

- name: wait for SSH to set up
  wait_for:
    host: "54.229.114.204"
    port: 22
    delay: 10
    timeout: 100
    state: started

- name: Render etc hosts file
  become: true
  command: hostname
  delegate_to: "54.229.114.204"
