---
- name: create network for java servers 
  docker_network:
    name: java_network

- name: copy over the dockerfile for java application
  synchronize:
   src: files/
   dest: "{{ dockerfile_path }}"
   archive: yes
   links: yes

#- name: change the dockerfile permission
#  file:
#    path: "{{ dockerfile_path }}"
#   owner: ubuntu
#   group: ubuntu
#   mode: 0755

- name: build java environment from Dockerfile
  docker_image:
     name: "{{ image_name }}"
     tag: "{{ image_tag }}"
     state: present
     path: "{{ dockerfile_path }}"

- name: start the java container for server1 for .zip artifacts
  docker_container:
    name: "{{ zip_docker_name }}"
    image: "{{ java_image }}"
    privileged: true
    ports:
      - 5000:5000
    networks:
      - name: java_network

- name: start the java container for server2 for .war artifacts
  docker_container:
    name: "{{ war_docker_name }}"
    image: "{{ java_image }}"
    privileged: true
    ports:
      - 5001:5001
    networks:
      - name: java_network
